services:

  api:
    build: ./api
    container_name: motion_api

    ports:
      - "8000:8000"

    volumes:
      - ./dataset:/app/dataset
      - ./config.json:/app/config.json

  simulator:
    build: ./simulator
    container_name: motion_simulator

    volumes:
      - ./config.json:/app/config.json

    depends_on:
      - api

  trainer:
    build: ./trainer
    container_name: ml_trainer

    volumes:
      - ./dataset:/app/dataset
      - ./model:/app/model
      - ./config.json:/app/config.json

    depends_on:
      - api